#version of docker compose 
version: '3.8'
# list of servicies
services:
  #container 1
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
  #container 2
  mongodb-express:
    image: mongo-express
    ports:
      - "8080:8081"
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "admin"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "password"
      ME_CONFIG_MONGODB_SERVER: "mongodb"
